# Generated by Django 3.1.7 on 2022-11-19 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 17, 12, 19, 373322, tzinfo=utc)),
        ),
    ]
